=== ubports/installer-configs/v1/_device.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/ubports/installer-configs/master/v1/_device.schema.json",
  "title": "Device",
  "description": "Device configuration for the UBports Installer",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The human-readable name under which the device was marketed. This includes the name of the manufacturer if it makes sense. I.e. you would not refer to the 'Oneplus One' as 'One', but you would not call the 'iPhone 9' 'Apple iPhone 9'. Use common sense."
    },
    "codename": {
      "type": "string",
      "description": "A short codename that is used internally to identify the device. This (with the extension '.json') should also be the filename. If there are multiple codenames in use for the exact same device, only create a single one with the most prominent one and add the correct aliases to aliases.json."
    },
    "user_actions": {
      "type": "object",
      "description": "Object that contains instructions for the user for later reference.",
      "patternProperties": {
        "\\w": {
          "type": "object",
          "description": "Instruction that can be referenced and presented to the user. Eg key combinations to reboot to recovery or bootloader.",
          "properties": {
            "title": {
              "type": "string",
              "description": "Identifier of the step. Eg. 'Enable USB-debugging'"
            },
            "description": {
              "type": "string",
              "description": "Short description of the step. For simple tasks, the full instructions can be put here."
            },
            "image": {
              "type": "string",
              "description": "String referring to a picture in the installer.",
              "enum": [
                "phone_power_up",
                "phone_power_down"
              ]
            },
            "button": {
              "type": "boolean",
              "description": "Specify whether there should be a done-button displayed."
            },
            "link": {
              "type": "string",
              "description": "A link to a more extensive tutorial."
            }
          },
          "required": [
            "title",
            "description"
          ]
        }
      }
    },
    "unlock": {
      "type": "array",
      "description": "An array of strings referring to user_actions defined above that are needed to unlock the device. This might include simple things like enabling adb access or bigger steps like using a leaked oem tool to flash highly questionable images that unlock the bootloader. Whatever is needed to make installations possible.",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "operating_systems": {
      "type": "array",
      "description": "An array of objects describing operating systems available for installation.",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "description": "An operating system available for installation",
        "properties": {
          "name": {
            "type": "string",
            "description": "Human-readable name of the operating system."
          },
          "options": {
            "type": "array",
            "description": "Options for the installation.",
            "items": {
              "type": "object",
              "description": "Option for the installation.",
              "properties": {
                "var": {
                  "type": "string",
                  "description": "Variable the setting will be stored in."
                },
                "name": {
                  "type": "string",
                  "description": "Human-readable identifier of the setting."
                },
                "tooltip": {
                  "type": "string",
                  "description": "A very short help text describing the setting."
                },
                "link": {
                  "type": "string",
                  "description": "A link to the docs describing the setting."
                },
                "type": {
                  "type": "string",
                  "description": "Describes what values are accepted by the setting and how they are provided.",
                  "enum": [
                    "checkbox",
                    "input",
                    "select"
                  ]
                },
                "remote_values": {
                  "type": "object",
                  "description": "If the values can be generated from a remote source like the systemimage api, this provides the required information for that.",
                  "properties": {
                    "type": {
                      "type": "string",
                      "enum": ["systemimagechannels"]
                    }
                  }
                },
                "value": {
                  "description": "Default value of the option"
                },
                "values": {
                  "type": "array",
                  "description": "List of values for the select."
                }
              },
              "required": [
                "var",
                "name",
                "type"
              ]
            }
          },
          "prerequisites": {
            "type": "array",
            "description": "An array of strings referring to user_actions defined above that are needed before the installation. This should not include the steps from the generic unlock block, but actions specific to the installation of this operating system.",
            "values": {
              "type": "string",
              "description": "Reference to user_action that's needed before the installation of this OS. Steps required for every OS should be put in the generic unlock block instead."
            }
          },
          "steps": {
            "type": "array",
            "description": "An ordered array of objects describing steps required to install the operating system.",
            "items": {
              "type": "object",
              "description": "Installation step.",
              "properties": {
                "type": {
                  "type": "string",
                  "description": "Type of installation step.",
                  "enum": [
                    "user_action",
                    "fastboot:reboot_bootloader",
                    "fastboot:update",
                    "systemimage",
                    "fastboot:boot",
                    "fastboot:reboot",
                    "fastboot:continue",
                    "fastboot:erase",
                    "fastboot:format",
                    "fastboot:flash",
                    "adb:reboot",
                    "adb:format",
                    "download"
                  ]
                },
                "optional": {
                  "type": "boolean",
                  "description": "If true, errors in this step will be ignored"
                },
                "fallback_user_action": {
                  "type": "string",
                  "description": "Reference to a user_action that can be used if the step fails."
                },
                "condition": {
                  "type": "object",
                  "description": "Query an installation option to determine if the step should be run",
                  "properties": {
                    "var": {
                      "type": "string",
                      "description": "Reference to an option defined for this operating system"
                    },
                    "value": {
                      "description": "Value to expect"
                    }
                  },
                  "required": ["var", "value"]
                },
                "group": {
                  "type": "string",
                  "description": "[type: download] [required] Group of files."
                },
                "files": {
                  "type": "array",
                  "description": "[type: download] [required] Array of files to download.",
                  "items": {
                    "type": "object",
                    "properties": {
                      "url": {
                        "type": "string",
                        "description": "URL of the file to download"
                      },
                      "checksum": {
                        "type": "string",
                        "description": "Checksum (sha256) of the file to download"
                      }
                    },
                    "required": ["url"]
                  }
                },
                "partition": {
                  "type": "string",
                  "description": "[type: adb:format] [required] Partition to format."
                },
                "to_state": {
                  "type": "string",
                  "description": "[type: adb:reboot] [required] State to rebot to.",
                  "enum": ["recovery", "system", "bootloader"]
                }
              },
              "required": ["type"]
            }
          },
          "slideshow": {
            "type": "array",
            "description": "An array of slides presenting the operating system's most compelling features.",
            "items": {
              "type": "object",
              "description": "Slide about the operating system",
              "properties": {
                "title": {
                  "type": "string",
                  "description": "Title of the slide"
                },
                "text": {
                  "type": "string",
                  "description": "Text body of the slide, Markdown supported here."
                },
                "image": {
                  "type": "string",
                  "description": "Image displayed on the slide."
                }
              }
            }
          },
          "video": {
            "type": "string",
            "description": "A video introducing the user to the operating system they just installed."
          },
          "donate": {
            "type": "string",
            "description": "A link to donate to the developer of the operating system."
          },
          "get_involved": {
            "type": "string",
            "description": "A link to the OSs get involved page."
          }
        }
      }
    }
  },
  "required": [
    "name",
    "codename",
    "operating_systems"
  ]
}

=== ubports/installer-configs/v1/arale.json
{
  "name": "Meizu MX4",
  "codename": "arale",
  "unlock": ["unlock"],
  "user_actions": {
    "recovery": {
      "title": "Reboot to Recovery",
      "description": "Press and hold the volume up and power buttons until the phone reboots.",
      "image": "phone_power_up",
      "button": true
    },
    "bootloader": {
      "title": "Reboot to Bootloader",
      "description": "Press and hold the volume down and power buttons until the phone reboots.",
      "image": "phone_power_down",
      "button": true
    },
    "unlock": {
      "title": "Unlock",
      "description": "If the device is running Android, it needs to be manually unlocked for the Installer to work. This is achieved by first installing a very old version of Canonical's Ubuntu Touch using an OEM tool, which is a manual process. Click the link below to find out more. If the device is already running Ubuntu Touch, you can simply ignore this message.",
      "link": "https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices"
    }
  },
  "operating_systems": [
    {
      "name": "Ubuntu Touch",
      "sanity_check": "Are you sure?",
      "options": [
        {
          "var": "channel",
          "name": "Channel",
          "tooltip": "The release channel",
          "link": "https://docs.ubports.com/en/latest/about/process/release-schedule.html",
          "type": "select",
          "remote_values": { "type": "systemimagechannels" }
        },
        {
          "var": "wipe",
          "name": "Wipe Userdata",
          "tooltip": "Wipe personal data",
          "type": "checkbox"
        },
        {
          "var": "bootstrap",
          "name": "Bootstrap",
          "tooltip": "Flash system partitions using fastboot",
          "type": "checkbox",
          "value": true
        }
      ],
      "prerequisites": [],
      "steps": [
        {
          "type": "download",
          "condition": {"var": "bootstrap", "value": true},
          "group": "recovery",
          "files": [
            {
              "url": "http://cdimage.ubports.com/devices/recovery-arale.img",
              "checksum": "27160d1ce2d55bd940b38ebf643018b33e0516795dff179942129943fabdc3d8"
            }
          ]
        },
        {
          "type": "adb:reboot",
          "condition": {"var": "bootstrap", "value": true},
          "to_state": "bootloader",
          "fallback_user_action": "bootloader"
        },
        {
          "type": "fastboot:flash",
          "condition": {"var": "bootstrap", "value": true},
          "flash": [
            {
              "partition": "recovery",
              "file": "recovery-arale.img",
              "group": "recovery"
            }
          ]
        },
        {
          "type": "fastboot:boot",
          "condition": {"var": "bootstrap", "value": true},
          "file": "recovery-arale.img",
          "fallback_user_action": "recovery",
          "group": "recovery"
        },
        {
          "type": "adb:reboot",
          "condition": {"var": "bootstrap", "value": false},
          "to_state": "recovery",
          "fallback_user_action": "recovery"
        },
        {
          "type": "adb:format",
          "partition": "cache"
        },
        {
          "type": "adb:reboot",
          "to_state": "recovery",
          "fallback_user_action": "recovery"
        },
        {
          "type": "systemimage"
        },
        {
          "type": "adb:reboot",
          "to_state": "recovery",
          "fallback_user_action": "recovery"
        }
      ],
      "slideshow": []
    }
  ]
}

=== ubports/installer-configs/v1/suzu.json
{
  "name": "Sony Xperia X",
  "codename": "suzu",
  "unlock": [],
  "user_actions": {
    "recovery": {
      "title": "Reboot to Recovery",
      "description": "With the device powered off, hold Volume Down + Power.",
      "image": "phone_power_down",
      "button": true
    },
    "bootloader": {
      "title": "Reboot to Bootloader",
      "description": "With the device powered off, hold Volume Up + Power. The LED indicator has to light up blue.",
      "image": "phone_power_up",
      "button": true
    },
    "boot": {
      "title": "Boot the device",
      "description": "Power on the device.",
      "image": "phone_power_up",
      "button": true
    }
  },
  "operating_systems": [
    {
      "name": "Ubuntu Touch",
      "sanity_check": "Are you sure?",
      "options": [
        {
          "var": "channel",
          "name": "Channel",
          "tooltip": "The release channel",
          "link": "https://docs.ubports.com/en/latest/about/process/release-schedule.html",
          "type": "select",
          "remote_values": { "type": "systemimagechannels" }
        },
        {
          "var": "wipe",
          "name": "Wipe Userdata",
          "tooltip": "Wipe personal data",
          "type": "checkbox"
        },
        {
          "var": "bootstrap",
          "name": "Bootstrap",
          "tooltip": "Flash system partitions using fastboot",
          "type": "checkbox",
          "value": true
        }
      ],
      "prerequisites": [],
      "steps": [
        {
          "type": "download",
          "condition": {"var": "bootstrap", "value": true},
          "group": "firmware",
          "files": [
            {
              "url": "https://ci.ubports.com/view/Device%20Builds/job/halium-suzu/lastSuccessfulBuild/artifact/halium-boot_suzu.img"
            },
            {
              "url": "https://ci.ubports.com/view/Device%20Builds/job/halium-suzu/lastSuccessfulBuild/artifact/halium-unlocked-recovery_suzu.img"
            }
          ]
        },
        {
          "type": "adb:reboot",
          "condition": {"var": "bootstrap", "value": true},
          "to_state": "bootloader",
          "fallback_user_action": "bootloader"
        },
        {
          "type": "fastboot:flash",
          "condition": {"var": "bootstrap", "value": true},
          "flash": [
            {
              "partition": "boot",
              "file": "halium-boot_suzu.img",
              "group": "firmware"
            },
            {
              "partition": "recovery",
              "file": "halium-unlocked-recovery_suzu.img",
              "group": "firmware"
            }
          ]
        },
        {
          "type": "fastboot:erase",
          "condition": {"var": "bootstrap", "value": true},
          "partition": "cache"
        },
        {
          "type": "fastboot:flash",
          "condition": {"var": "bootstrap", "value": true},
          "flash": [
            {
              "partition": "boot",
              "file": "halium-unlocked-recovery_suzu.img",
              "group": "firmware"
            },
            {
              "partition": "recovery",
              "file": "halium-unlocked-recovery_suzu.img",
              "group": "firmware"
            }
          ],
          "group": "firmware"
        },
        {
          "type": "fastboot:reboot",
          "fallback_user_action": "boot",
          "group": "firmware"
        },
        {
          "type": "systemimage"
        },
        {
          "type": "adb:reboot",
          "to_state": "recovery",
          "fallback_user_action": "recovery"
        }
      ],
      "slideshow": []
    }
  ]
}
